//
//  CityWeathereListModels.swift
//  NatiaL_HW27
//
//  Created by Natia's Mac on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum CityWeathereList
{
  // MARK: Use cases
  enum ShowWeatherList
  {
    struct Request
    {
    }
    struct Response
    {
        let weatherResponse : WeatherResponse
    }
    struct ViewModel
    {
          
            let tempInCity: WeatherResponse
    
    }
  }
    enum showWeatherDetails {
        struct Request
        {
            let weatherResponse : WeatherResponse
        }
        struct Response
        {
           
        }
        struct ViewModel
        {
        }
    }
}
