//
//  CityWeathereListWorker.swift
//  NatiaL_HW27
//
//  Created by Natia's Mac on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
protocol WeatherWorkerLogic {
    func fetchWeatherInfo() async throws -> WeatherResponse
}
class CityWeathereListWorker {
    private var apiManager: APIManager
    private let urlString = "https://api.openweathermap.org/data/2.5/weather?q=Tbilisi&appid=d5c2719b70bede754fd091abd81c81b0"
    
    init(apiManager: APIManager) {
        self.apiManager = apiManager
    }
    
  func fetchWeatherInfo() async throws -> WeatherResponse {
      try await apiManager.fetchData(urlString: urlString, decodingType: WeatherResponse.self)
  }
}
