//
//  CityWeathereListRouter.swift
//  NatiaL_HW27
//
//  Created by Natia's Mac on 30.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CityWeathereListRoutingLogic
{
  func navigateToCountryDetails()
}

protocol CityWeathereListDataPassing
{
  var dataStore: CityWeathereListDataStore? { get }
}

class CityWeathereListRouter: NSObject, CityWeathereListRoutingLogic, CityWeathereListDataPassing
{
    
    
  weak var viewController: CityWeathereListViewController?
  private(set) var dataStore: CityWeathereListDataStore?
  
    
    init(dataStore: CityWeathereListDataStore) {
        self.dataStore = dataStore
    }
  // MARK: Routing
    
    func navigateToCountryDetails() {
        guard let selectedCity = dataStore?.selectedWeather else { return }
        let destinationVC = DetailedWeatherConfiguration.configure(with: selectedCity)
        viewController?.navigationController?.pushViewController(destinationVC, animated: true)
        
    }
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: CityWeathereListViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: CityWeathereListDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
