//
//  DetailedWeatherInteractor.swift
//  NatiaL_HW27
//
//  Created by Natia's Mac on 31.08.22.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol DetailedWeatherBusinessLogic
{
  func getDetails(request: DetailedWeather.ShowWeatherDetails.Request)
}

protocol DetailedWeatherDataStore
{
}

class DetailedWeatherInteractor: DetailedWeatherBusinessLogic, DetailedWeatherDataStore
{
  var presenter: DetailedWeatherPresentationLogic?
  var passedObject: WeatherResponse?
  
  // MARK: Do something
  
    init(presenter: DetailedWeatherPresentationLogic, passedObject: WeatherResponse) {
        self.presenter = presenter
        self.passedObject = passedObject
    }
  func getDetails(request: DetailedWeather.ShowWeatherDetails.Request)
  {

      guard let passedObject = passedObject else {
          return
      }
      let response = DetailedWeather.ShowWeatherDetails.Response(weatherResponse: passedObject)
      presenter?.presentWeatherInfo(response: response)
  }
}
